// Portfolio Data - All content structured separately for easy updates

export const portfolioData = {
  personal: {
    name: "Prashant Kumar Maurya",
    title: "Full Stack Developer",
    subtitle: "Building production-grade applications with modern tech stack",
    roles: ["Frontend Developer", "Backend Developer", "Full Stack Engineer"],
    email: "prashantmaurya252@outlook.com",
    phone: "+91 6306315885",
    resumeLink: "https://drive.google.com/file/d/1n9vFDWZ9iicudFcmC_8WNE6iHElQ-RcQ/view?usp=sharing",
    bio: "2+ years of proven expertise in building production-grade web applications using MERN stack & PostgreSQL. Specialized in secure authentication, real-time features, cloud integrations, and complex approval workflows.",
    social: {
      github: "https://github.com/PrashantMaurya252",
      linkedin: "https://linkedin.com/in/prashant-kumar-maurya",
      email: "prashantmaurya252@outlook.com",
    },
  },

  skills: {
    "Languages": ["JavaScript (ES6+)", "TypeScript", "HTML5", "CSS3", "SQL"],
    "Frontend": ["React.js", "Next.js", "Tailwind CSS", "Redux Toolkit", "Framer Motion", "ShadCN UI", "Material UI"],
    "Backend": ["Node.js", "Express.js", "Socket.io", "RESTful APIs", "Microservices"],
    "Databases": ["PostgreSQL", "MongoDB", "Prisma ORM", "Mongoose", "Query Optimization"],
    "Cloud & DevOps": ["AWS (S3, EC2)", "Azure (OCR)", "Firebase", "Docker (Basic)", "GitHub Actions"],
    "Security & Auth": ["JWT", "OAuth2", "RBAC", "Bcrypt", "Secure Cookies"],
    "Tools & APIs": ["Git", "GitHub", "Stripe", "OpenAI", "Socket.io", "Postman"],
  },

  experience: [
    {
      role: "Full Stack Developer",
      company: "Codenia Technologies LLP",
      period: "Feb 2025 – Present",
      description: "Building enterprise-grade applications with complex workflows",
      highlights: [
        "Architected 4+ production-grade full stack projects including Employee Expense Management & Insurance Platform",
        "Designed enterprise authentication with JWT, refresh tokens, RBAC supporting 6+ user roles",
        "Built complex approval workflows with configurable auto-approval triggers & audit systems",
        "Architected RESTful APIs with centralized middleware reducing debugging time by 60%",
        "Optimized database schemas improving query performance by 45%",
        "Integrated OpenAI chatbot and Azure OCR for automated document processing (70% time savings)",
        "Engineered real-time features with Socket.io achieving 99.8% uptime",
        "Resolved critical production issues through systematic debugging & optimization",
      ],
      icon: "material-symbols:work",
    },
    {
      role: "Frontend Developer Intern",
      company: "Virtual Cybertrons",
      period: "Apr 2024 – Jan 2025",
      description: "Developed UI components and integrated multiple APIs",
      highlights: [
        "Developed modular, reusable UI components using Next.js, React, Tailwind CSS",
        "Architected authentication flows with Firebase Authentication for social login",
        "Integrated 25+ APIs with intelligent caching reducing network requests by 30%",
        "Implemented accessible UI components for seamless cross-platform experience",
        "Collaborated with backend teams on API design & technical specifications",
        "Optimized frontend performance through code splitting & lazy loading",
      ],
      icon: "material-symbols:school",
    },
  ],

  projects: [
    {
      id: 1,
      title: "Full Stack E-Commerce Platform",
      description: "Type-safe e-commerce platform with secure payments, inventory management, and optimized queries",
      image: "🛍️",
      tags: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "TypeScript", "Prisma"],
      highlights: [
        "JWT + Google OAuth authentication",
        "Stripe Payment Intents with webhook handling",
        "Real-time inventory & shopping cart",
        "Advanced product filtering & search",
        "Order history & dispute tracking",
      ],
      githubLink: "https://github.com/PrashantMaurya252/ecommerce-platform",
      deployedLink: "https://ecommerce-platform-demo.vercel.app",
      features: ["Multi-faceted search", "Secure payments", "Real-time updates"],
      stats: {
        performance: "98",
        responsive: "100",
        security: "95",
      },
    },
    {
      id: 2,
      title: "Instagram Clone",
      description: "Real-time social networking platform with live chat, notifications, and image optimization",
      image: "📱",
      tags: ["MERN", "Socket.io", "Redux", "Cloudinary", "MongoDB"],
      highlights: [
        "Real-time messaging with Socket.io",
        "Live notifications for likes & comments",
        "60% image optimization using Cloudinary",
        "User profiles & follow system",
        "Nested comments & bookmarks",
      ],
      githubLink: "https://github.com/PrashantMaurya252/instagram-clone",
      deployedLink: "https://instagram-clone-demo.vercel.app",
      features: ["Real-time chat", "Image optimization", "Social features"],
      stats: {
        performance: "96",
        responsive: "100",
        features: "98",
      },
    },
    {
      id: 3,
      title: "MERN Blog Platform",
      description: "Full-featured blogging platform with analytics dashboard and role-based access control",
      image: "📝",
      tags: ["MERN", "Redux", "Firebase", "Vite", "MongoDB"],
      highlights: [
        "Admin analytics dashboard with 30-day trends",
        "Full-text search & category filtering",
        "Draft/publish workflow",
        "Role-based access control",
        "Dark/light theme switching",
      ],
      githubLink: "https://github.com/PrashantMaurya252/blog-platform",
      deployedLink: "https://blog-platform-demo.vercel.app",
      features: ["Analytics", "Search", "RBAC"],
      stats: {
        performance: "97",
        responsive: "100",
        usability: "99",
      },
    },
  ],

  certifications: [
    {
      id: 1,
      title: "SQL and PostgreSQL: The Complete Developer's Guide",
      issuer: "Udemy",
      date: "2024",
      icon: "mdi:database",
      certificateLink: "https://udemy.com/certificate/UC-XXXXX",
      skills: ["SQL", "PostgreSQL", "Query Optimization"],
    },
    {
      id: 2,
      title: "Full Stack Development Bootcamp – MERN Stack",
      issuer: "upGrad",
      date: "2024",
      icon: "mdi:code-braces",
      certificateLink: "https://upgradcertificate.com/XXXXX",
      skills: ["MERN Stack", "Web Development", "Project Management"],
    },
    {
      id: 3,
      title: "Advanced JavaScript & ES6+",
      issuer: "Udemy",
      date: "2023",
      icon: "mdi:language-javascript",
      certificateLink: "https://udemy.com/certificate/JS-XXXXX",
      skills: ["JavaScript", "ES6", "Async Programming"],
    },
  ],

  themes: [
    {
      id: "cyberpunk",
      name: "Cyberpunk",
      colors: {
        primary: "from-pink-500 to-cyan-400",
        secondary: "from-purple-600 to-pink-500",
        accent: "pink-500",
        bg: "bg-slate-950",
        text: "text-pink-50",
        card: "bg-slate-900/80",
        border: "border-pink-500/30",
      },
      icon: "mdi:robot",
    },
    {
      id: "luxury",
      name: "Luxury",
      colors: {
        primary: "from-yellow-500 to-amber-600",
        secondary: "from-amber-700 to-yellow-600",
        accent: "yellow-500",
        bg: "bg-slate-950",
        text: "text-amber-50",
        card: "bg-slate-900/80",
        border: "border-yellow-600/30",
      },
      icon: "mdi:crown",
    },
    {
      id: "ocean",
      name: "Ocean",
      colors: {
        primary: "from-blue-500 to-teal-400",
        secondary: "from-teal-600 to-blue-500",
        accent: "blue-400",
        bg: "bg-slate-950",
        text: "text-blue-50",
        card: "bg-slate-900/80",
        border: "border-blue-500/30",
      },
      icon: "mdi:water",
    },
    {
      id: "forest",
      name: "Forest",
      colors: {
        primary: "from-green-500 to-emerald-400",
        secondary: "from-emerald-600 to-green-500",
        accent: "green-500",
        bg: "bg-slate-950",
        text: "text-green-50",
        card: "bg-slate-900/80",
        border: "border-green-500/30",
      },
      icon: "mdi:tree",
    },
    {
      id: "sunset",
      name: "Sunset",
      colors: {
        primary: "from-orange-500 to-red-500",
        secondary: "from-purple-600 to-orange-500",
        accent: "orange-500",
        bg: "bg-slate-950",
        text: "text-orange-50",
        card: "bg-slate-900/80",
        border: "border-orange-500/30",
      },
      icon: "mdi:sun-setting",
    },
    {
      id: "midnight",
      name: "Midnight",
      colors: {
        primary: "from-indigo-500 to-blue-600",
        secondary: "from-blue-600 to-indigo-500",
        accent: "indigo-400",
        bg: "bg-slate-950",
        text: "text-indigo-50",
        card: "bg-slate-900/80",
        border: "border-indigo-500/30",
      },
      icon: "mdi:moon-waning-crescent",
    },
  ],
};